version: '3'

services:
  Valhalla:
    image: traefik:v1.7
    networks:
      - web
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.config/traefik/traefik.toml:/traefik.toml
      - ./.config/traefik/acme.json:/acme.json

  Moneta:
    image: ${MONETA_IMAGE}
    depends_on:
      - Redis
    environment:
      - NCRYPT_API_API_BASE_URL=${NCRYPT_API_API_BASE_URL}
      - NCRYPT_API_APP_BASE_URL=${NCRYPT_API_APP_BASE_URL}
      - NCRYPT_API_STORAGE_DRIVER=${NCRYPT_API_STORAGE_DRIVER}
      - NCRYPT_API_REDIS_HOST=${NCRYPT_API_REDIS_HOST}
      - NCRYPT_API_REDIS_PORT=${NCRYPT_API_REDIS_PORT}
      - NCRYPT_API_REDIS_DB=${NCRYPT_API_REDIS_DB}
      - NCRYPT_API_REDIS_PASSWORD=${NCRYPT_API_REDIS_PASSWORD}
    expose:
      - "1990"
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.ncrypt.site"
      - "traefik.basic.port=1990"
      - "traefik.basic.protocol=http"

  Redis:
    image: redis:6-alpine
    labels:
      - "traefik.enable=false"

  Aphrodite:
    image: ${APHRODITE_IMAGE}
    expose:
      - "80"
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ncrypt.site"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

networks:
  web:
    external: true